### ISSUE TITLE
dirigent create command

### ISSUE THREAD

**Issue by weitenghuang** [weitenghuang/dirigent-cli#6]
`dirigent create` will take user's `docker-compose` file and create specific kubernetes resource.

Input `docker-compose` file for dirigent-cli docker container

``` yaml
version: "2"

services:
  rethink:
    image: quay.io/concur_platform/rethinkdb:2.2.6-ead3acc
    ports:
      - "28015:28015"
      - "29015:29015"
      - "8080:8080"
    volumes:
      - "./rethinkdb-data:/data"
  web:
    image: quay.io/concur_platform/node-skeleton
    environment:
      RETHINK_HOST: "rethink-service.default.svc.cluster.local"
    command: node src/index.js
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/opt/concur/service
      - node_modules:/opt/concur/service/node_modules
    links:
      - rethink

volumes:
  node_modules:
    driver: local
```

``` sh
$ dirigent create kubernetes replicationcontroller
```

Output will be 

``` sh
rc-web.yml
rc-rethink.yml
```

rc-web.yml:

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    name: web-latest-rc
  name: web-latest-rc
  namespace: default
spec:
  replicas: 1
  selector:
    name: web-latest-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: web-latest-pod
      name: web-latest-pod
      namespace: default
    spec:
      containers:
      - command:
        - node
        - src/index.js
        env:
        - name: RETHINK_HOST
          value: rethink-service.default.svc.cluster.local
        image: quay.io/concur_platform/node-skeleton
        imagePullPolicy: IfNotPresent
        name: web-container
        ports:
        - containerPort: 3000
          name: port-3000
          protocol: TCP
        - containerPort: 5858
          name: port-5858
          protocol: TCP
        resources: {}
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
```
